# Generated by Django 4.1.4 on 2022-12-09 15:19

import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone
import user.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('firstname', models.CharField(max_length=100, null=True)),
                ('lastname', models.CharField(max_length=100, null=True)),
                ('fathername', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(max_length=255, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.CharField(choices=[['DEAN', 'DEAN'], ['STAFF', 'STAFF'], ['STUDENT', 'STUDENT']], max_length=15)),
                ('JSHIR', models.CharField(max_length=14, unique=True)),
                ('passport_number', models.CharField(max_length=10)),
                ('profile_image', models.ImageField(upload_to='profile_image/')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', user.manager.CustomUserManager()),
            ],
        ),
    ]
